sudo: false
language: php

php:
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_script:
  - git clone --depth=50 --branch=2017.07 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-filesystem ext/
  - composer require league/flysystem-aws-s3-v3 league/flysystem-dropbox league/flysystem-gridfs league/flysystem-memory league/flysystem-rackspace league/flysystem-replicate-adapter league/flysystem-sftp league/flysystem-webdav jackalope/jackalope-doctrine-dbal league/flysystem-phpcr league/flysystem-ziparchive

script:
  - vendor/bin/phing -Ddir=ext/ai-filesystem coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-filesystem/.coveralls.yml

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
