# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

jobs:
  "php81":
    docker:
      - image: aimeos/ci-php:8.1
    steps:
      - checkout
      - run: git clone --depth=50 --branch=master https://github.com/aimeos/aimeos-core ../aimeos-core
      - run: cd .. && mv project aimeos-core/ext/ai-filesystem && mv aimeos-core project && cd project
      - restore_cache:
          keys:
            - php81-{{ checksum "composer.json" }}
      - run: composer req --no-update league/flysystem-aws-s3-v3 league/flysystem-azure-blob-storage spatie/flysystem-dropbox league/flysystem-google-cloud-storage league/flysystem-ftp league/flysystem-memory league/flysystem-sftp league/flysystem-webdav league/flysystem-ziparchive
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php81-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phing -Ddir=ext/ai-filesystem testext

  "php82":
    docker:
      - image: aimeos/ci-php:8.2
    steps:
      - checkout
      - run: git clone --depth=50 --branch=master https://github.com/aimeos/aimeos-core ../aimeos-core
      - run: cd .. && mv project aimeos-core/ext/ai-filesystem && mv aimeos-core project && cd project
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer req --no-update league/flysystem-aws-s3-v3 league/flysystem-azure-blob-storage spatie/flysystem-dropbox league/flysystem-google-cloud-storage league/flysystem-ftp league/flysystem-memory league/flysystem-sftp league/flysystem-webdav league/flysystem-ziparchive
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phing -Ddir=ext/ai-filesystem coverageext
      - run: ./vendor/bin/php-coveralls --root_dir ext/ai-filesystem -o coveralls.json -vvv -x tests/coverage.xml

  "php83":
    docker:
      - image: aimeos/ci-php:8.3
    steps:
      - checkout
      - run: git clone --depth=50 --branch=master https://github.com/aimeos/aimeos-core ../aimeos-core
      - run: cd .. && mv project aimeos-core/ext/ai-filesystem && mv aimeos-core project && cd project
      - restore_cache:
          keys:
            - php83-{{ checksum "composer.json" }}
      - run: composer req --no-update league/flysystem-aws-s3-v3 league/flysystem-azure-blob-storage spatie/flysystem-dropbox league/flysystem-google-cloud-storage league/flysystem-ftp league/flysystem-memory league/flysystem-sftp league/flysystem-webdav league/flysystem-ziparchive
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php83-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phing -Ddir=ext/ai-filesystem testext

  "php84":
    docker:
      - image: aimeos/ci-php:8.4
    steps:
      - checkout
      - run: git clone --depth=50 --branch=master https://github.com/aimeos/aimeos-core ../aimeos-core
      - run: cd .. && mv project aimeos-core/ext/ai-filesystem && mv aimeos-core project && cd project
      - restore_cache:
          keys:
            - php84-{{ checksum "composer.json" }}
      - run: composer req --no-update league/flysystem-aws-s3-v3 league/flysystem-azure-blob-storage spatie/flysystem-dropbox league/flysystem-google-cloud-storage league/flysystem-ftp league/flysystem-memory league/flysystem-sftp league/flysystem-webdav league/flysystem-ziparchive
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php84-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phing -Ddir=ext/ai-filesystem testext

workflows:
  version: 2
  unittest:
    jobs:
      - "php81"
      - "php82"
      - "php83"
      - "php84"
